steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/area-control-loop',
      '--build-arg', 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}',
      '--build-arg', 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}',
      '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}',
      '--build-arg', 'VITE_API_URL=${_VITE_API_URL}',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/area-control-loop']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'area-control-loop',
      '--image', 'gcr.io/$PROJECT_ID/area-control-loop',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'GEMINI_API_KEY=${_GEMINI_API_KEY}',
      '--set-env-vars', 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}',
      '--set-env-vars', 'CORS_ORIGIN=${_CORS_ORIGIN}',
      '--port', '8080'
    ]
substitutions:
    _REGION: us-central1
images:
  - 'gcr.io/$PROJECT_ID/area-control-loop'
